# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Ubuntu 16.04.x:
  config.vm.box = "ubuntu/xenial64"

  # Run Ansible from the Vagrant Host
  config.vm.provision "ansible" do |ansible|
    ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
    ansible.playbook = "provisioning/playbook.yml"
    ansible.become = true
    ## Uncomment below for troubleshooting
    #ansible.verbose = "vvv"
    ## USE ask_become_pass on any case where vagrant 'ubuntu' user
    ## is not set to use NOPASSWD:
    #  ansible.ask_become_pass = true
  end

  config.vm.provider "virtualbox" do |vb|
    vb.name = "samvera-newspapers"
    vb.memory = 2048
  end

  # misc config:
  config.vm.hostname = "samvera-newspapers"
  config.vm.box_check_update = true

  # ssh agent forwarding for convenience:
  config.ssh.forward_agent = true

  # -- port forwarding --
  
  # forward TCP 3000 for rails/puma, only via local host interface:
  config.vm.network :forwarded_port, host_ip: "127.0.0.1", guest: 3000, host:3000
  # forward TCP 8983 for solr, only via local host interface:
  config.vm.network :forwarded_port, host_ip: "127.0.0.1", guest: 8983, host:8983
  # forward TCP 8984 for fcrepo, only via local host interface:
  config.vm.network :forwarded_port, host_ip: "127.0.0.1", guest: 8984, host:8984

  # Sync ./projects on host for access in guest at /home/ubuntu/projects
  config.vm.synced_folder "./projects", "/home/ubuntu/projects"

end
